version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - ginkgolinter
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - lll
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    depguard:
      rules:
        main:
          # Different modes: `original`, `strict`, and `lax`. Default: "original".
          list-mode: strict
          allow:
            - $gostd
            - go/format
            - go/token
            - golang.org/x/sync/errgroup
            - golang.org/x/sync/singleflight
            - golang.org/x/net/nettest
            - golang.org/x/crypto/bcrypt
            - golang.org/x/text
            - go.uber.org/mock/gomock
            - go.uber.org/goleak
            - go.uber.org/dig
            - github.com/stretchr/testif
            - github.com/assurrussa/goinertia
            - github.com/gofiber/fiber
            - github.com/gofiber/utils/v2
            - github.com/valyala/fasthttp
            - github.com/goccy/go-json
          deny:
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard pkg errors package
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    exhaustive:
      default-signifies-exhaustive: true
    forbidigo:
      forbid:
        - pattern: ^(fmt\.Print(|f|ln)|print|println)$
        - pattern: errors\.Wrap
        - pattern: errors\.Cause
    ginkgolinter:
      suppress-len-assertion: false
      suppress-nil-assertion: false
      suppress-err-assertion: false
      suppress-compare-assertion: false
      suppress-async-assertion: false
      allow-havelen-zero: false
    godox:
      keywords:
        - FIXME
        - TODO
    gosec:
      excludes:
        # G115: integer overflow conversion int -> uint64 https://github.com/moby/moby/issues/48358
        - G115
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    lll:
      line-length: 130
      tab-width: 1
    gomoddirectives:
      replace-local: true
    loggercheck:
      klog: false
      logr: false
      zap: true
      require-string-key: true
      no-printf-like: true
      rules:
        - (*go.uber.org/zap.SugaredLogger).With
    nolintlint:
      require-explanation: true
      allow-no-explanation:
        - lll
    perfsprint:
      # Optimizes `fmt.Sprintf` with only one argument.
      sprintf1: true
      # Optimizes `fmt.Sprintf` into string concatenation.
      str-concat: true
      # Optimizes `fmt.Errorf` into `errors.New`.
      errorf: true
      # Optimizes `fmt.Sprintf` with integer format specifier.
      int-conversion: true
      # Optimizes `fmt.Sprintf` with error format specifier.
      err-error: true
    prealloc:
      # Report preallocation suggestions only on simple loops.
      simple: true
      # Report preallocation suggestions on range loops.
      range-loops: true
      # Report preallocation suggestions on for loops.
      for-loops: true
    revive:
      severity: error
      rules:
        - name: argument-limit
        - name: atomic
        - name: bare-return
        - name: blank-imports
        - name: bool-literal-in-expr
        - name: comment-spacings
        - name: confusing-results
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T' # https://go-review.googlesource.com/c/lint/+/145237
        - name: context-keys-type
        - name: datarace
        - name: deep-exit
        - name: defer
        - name: dot-imports
        - name: duplicated-imports
        - name: early-return
        - name: empty-lines
        - name: empty-block
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: exported
        - name: identical-branches
        - name: if-return
        - name: increment-decrement
        - name: indent-error-flow
        - name: package-comments
        - name: range
        - name: range-val-address
        - name: range-val-in-closure
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: string-of-int
        - name: superfluous-else
        - name: time-equal
        - name: time-naming
        - name: unexported-return
        - name: unhandled-error
          arguments:
            - fmt.Fprint
            - fmt.Print
            - fmt.Printf
            - fmt.Println
        - name: unreachable-code
        - name: use-any
        - name: unused-parameter
        - name: var-declaration
        - name: var-naming
        - name: waitgroup-by-value
    tagliatelle:
      case:
        rules:
          json: camel
          toml: snake
          yaml: snake
        use-field-name: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
