// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks/inertia_mock.gen.go -package=goinertiamocks
//

// Package goinertiamocks is a generated GoMock package.
package goinertiamocks

import (
	context "context"
	reflect "reflect"

	fiber "github.com/gofiber/fiber/v3"
	gomock "go.uber.org/mock/gomock"

	goinertia "github.com/assurrussa/goinertia"
)

// MockSessionStore is a mock of SessionStore interface.
type MockSessionStore struct {
	ctrl     *gomock.Controller
	recorder *MockSessionStoreMockRecorder
	isgomock struct{}
}

// MockSessionStoreMockRecorder is the mock recorder for MockSessionStore.
type MockSessionStoreMockRecorder struct {
	mock *MockSessionStore
}

// NewMockSessionStore creates a new mock instance.
func NewMockSessionStore(ctrl *gomock.Controller) *MockSessionStore {
	mock := &MockSessionStore{ctrl: ctrl}
	mock.recorder = &MockSessionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionStore) EXPECT() *MockSessionStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSessionStore) Delete(c fiber.Ctx, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", c, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionStoreMockRecorder) Delete(c, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionStore)(nil).Delete), c, key)
}

// Flash mocks base method.
func (m *MockSessionStore) Flash(c fiber.Ctx, key string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flash", c, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Flash indicates an expected call of Flash.
func (mr *MockSessionStoreMockRecorder) Flash(c, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flash", reflect.TypeOf((*MockSessionStore)(nil).Flash), c, key, value)
}

// Get mocks base method.
func (m *MockSessionStore) Get(c fiber.Ctx, key string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", c, key)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSessionStoreMockRecorder) Get(c, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionStore)(nil).Get), c, key)
}

// GetFlash mocks base method.
func (m *MockSessionStore) GetFlash(c fiber.Ctx, key string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlash", c, key)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlash indicates an expected call of GetFlash.
func (mr *MockSessionStoreMockRecorder) GetFlash(c, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlash", reflect.TypeOf((*MockSessionStore)(nil).GetFlash), c, key)
}

// Set mocks base method.
func (m *MockSessionStore) Set(c fiber.Ctx, key string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", c, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockSessionStoreMockRecorder) Set(c, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockSessionStore)(nil).Set), c, key, value)
}

// MockSessionAdapter is a mock of SessionAdapter interface.
type MockSessionAdapter[T goinertia.FiberSessionStore] struct {
	ctrl     *gomock.Controller
	recorder *MockSessionAdapterMockRecorder[T]
	isgomock struct{}
}

// MockSessionAdapterMockRecorder is the mock recorder for MockSessionAdapter.
type MockSessionAdapterMockRecorder[T goinertia.FiberSessionStore] struct {
	mock *MockSessionAdapter[T]
}

// NewMockSessionAdapter creates a new mock instance.
func NewMockSessionAdapter[T goinertia.FiberSessionStore](ctrl *gomock.Controller) *MockSessionAdapter[T] {
	mock := &MockSessionAdapter[T]{ctrl: ctrl}
	mock.recorder = &MockSessionAdapterMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionAdapter[T]) EXPECT() *MockSessionAdapterMockRecorder[T] {
	return m.recorder
}

// Get mocks base method.
func (m *MockSessionAdapter[T]) Get(c fiber.Ctx) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", c)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSessionAdapterMockRecorder[T]) Get(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionAdapter[T])(nil).Get), c)
}

// MockFiberSessionStore is a mock of FiberSessionStore interface.
type MockFiberSessionStore struct {
	ctrl     *gomock.Controller
	recorder *MockFiberSessionStoreMockRecorder
	isgomock struct{}
}

// MockFiberSessionStoreMockRecorder is the mock recorder for MockFiberSessionStore.
type MockFiberSessionStoreMockRecorder struct {
	mock *MockFiberSessionStore
}

// NewMockFiberSessionStore creates a new mock instance.
func NewMockFiberSessionStore(ctrl *gomock.Controller) *MockFiberSessionStore {
	mock := &MockFiberSessionStore{ctrl: ctrl}
	mock.recorder = &MockFiberSessionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFiberSessionStore) EXPECT() *MockFiberSessionStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockFiberSessionStore) Delete(key any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", key)
}

// Delete indicates an expected call of Delete.
func (mr *MockFiberSessionStoreMockRecorder) Delete(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFiberSessionStore)(nil).Delete), key)
}

// Get mocks base method.
func (m *MockFiberSessionStore) Get(key any) any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(any)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockFiberSessionStoreMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFiberSessionStore)(nil).Get), key)
}

// Save mocks base method.
func (m *MockFiberSessionStore) Save() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save")
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockFiberSessionStoreMockRecorder) Save() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockFiberSessionStore)(nil).Save))
}

// Set mocks base method.
func (m *MockFiberSessionStore) Set(key, val any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", key, val)
}

// Set indicates an expected call of Set.
func (mr *MockFiberSessionStoreMockRecorder) Set(key, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockFiberSessionStore)(nil).Set), key, val)
}

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// DebugContext mocks base method.
func (m *MockLogger) DebugContext(ctx context.Context, msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "DebugContext", varargs...)
}

// DebugContext indicates an expected call of DebugContext.
func (mr *MockLoggerMockRecorder) DebugContext(ctx, msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DebugContext", reflect.TypeOf((*MockLogger)(nil).DebugContext), varargs...)
}

// ErrorContext mocks base method.
func (m *MockLogger) ErrorContext(ctx context.Context, msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ErrorContext", varargs...)
}

// ErrorContext indicates an expected call of ErrorContext.
func (mr *MockLoggerMockRecorder) ErrorContext(ctx, msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorContext", reflect.TypeOf((*MockLogger)(nil).ErrorContext), varargs...)
}

// InfoContext mocks base method.
func (m *MockLogger) InfoContext(ctx context.Context, msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "InfoContext", varargs...)
}

// InfoContext indicates an expected call of InfoContext.
func (mr *MockLoggerMockRecorder) InfoContext(ctx, msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoContext", reflect.TypeOf((*MockLogger)(nil).InfoContext), varargs...)
}

// WarnContext mocks base method.
func (m *MockLogger) WarnContext(ctx context.Context, msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "WarnContext", varargs...)
}

// WarnContext indicates an expected call of WarnContext.
func (mr *MockLoggerMockRecorder) WarnContext(ctx, msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarnContext", reflect.TypeOf((*MockLogger)(nil).WarnContext), varargs...)
}
